package ch.template.domain;

import android.os.Parcel;
import android.os.Parcelable;

import com.annimon.stream.Collector;
import com.annimon.stream.Stream;
import com.annimon.stream.function.BiConsumer;
import com.annimon.stream.function.Function;
import com.annimon.stream.function.Supplier;
import com.hannesdorfmann.parcelableplease.annotation.ParcelablePlease;

import java.util.ArrayList;
import java.util.List;

/**
 * To use ParcelablePlease, install the Android Studio plugin (not mandatory)
 */
@ParcelablePlease
public class TemplateDto implements Parcelable {

    List<String> list;

    public TemplateDto() {
        this.list = new ArrayList<>();
    }

    public void add(String str) {
        this.list.add(str);
    }

    public List<String> getList() {
        return list;
    }


    @Override
    public String toString() {
        if (list.size()==0) {
            return "[EMPTY]";
        }
        String representation = Stream.of(list)
                .map(item -> String.format("[%s]", item))
                .collect(new MyJoiner());
        return representation;
    }

    private static class MyJoiner implements Collector<String, StringBuilder, String> {

        private boolean first = true;

        @Override
        public Supplier<StringBuilder> supplier() {
            return () -> new StringBuilder();
        }

        @Override
        public BiConsumer<StringBuilder, String> accumulator() {
            return (value1, value2) -> {
                if (first) {
                    first = false;
                } else {
                    value1.append("-");
                }
                value1.append(value2);
            };
        }

        @Override
        public Function<StringBuilder, String> finisher() {
            return stringBuilder -> stringBuilder.toString();
        }
    }

    /*

        GENERATED BY PARCELABLE PLEASE

     */

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        TemplateDtoParcelablePlease.writeToParcel(this, dest, flags);
    }

    public static final Creator<TemplateDto> CREATOR = new Creator<TemplateDto>() {
        public TemplateDto createFromParcel(Parcel source) {
            TemplateDto target = new TemplateDto();
            TemplateDtoParcelablePlease.readFromParcel(target, source);
            return target;
        }

        public TemplateDto[] newArray(int size) {
            return new TemplateDto[size];
        }
    };
}
